services:
  app:
    build: .
    container_name: emotion-detection
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001 