# Add to your render.yaml
services:
  - type: web
    name: emotion-detection
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticDirs:
      - source: ./public
        destination: /