# Configuration pour déploiement sur Render.com
services:
  - type: web
    name: emotion-detection
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1