   # Add to your render.yaml
   services:
     - type: web
       name: emotion-detection
       env: node
       buildCommand: npm install
       startCommand: node server.js
       staticDirs:
         - source: ./models
           destination: /models
         - source: ./js
           destination: /js